export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAILURE = "PRODUCT_LIST_FAILURE";

export const PRODUCT_REQUEST = "PRODUCT__REQUEST";
export const PRODUCT__SUCCESS = "PRODUCT__SUCCESS";
export const PRODUCT__FAILURE = "PRODUCT_FAILURE";
