export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAILURE = "USER_REGISTER_FAILURE";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAILURE = "USER_REGISTER_FAILURE";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAILURE = "USER_LIST_FAILURE";
export const USER_LIST_RESET = "USER_LIST_RESET";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "USER_LIST_FAILURE";

export const GET_USER_DETAILS_BY_ID_REQUEST = "GET_USER_DETAILS_BY_ID_REQUEST";
export const GET_USER_DETAILS_BY_ID_SUCCESS = "GET_USER_DETAILS_BY_ID_SUCCESS";
export const GET_USER_DETAILS_BY_ID_FAILURE = "GET_USER_DETAILS_BY_ID_FAILURE";

export const USER_UPDATE_BY_ID_REQUEST = "USER_UPDATE_BY_ID_REQUEST";
export const USER_UPDATE_BY_ID_SUCCESS = "USER_UPDATE_BY_ID_SUCCESS";
export const USER_UPDATE_BY_ID_FAILURE = "USER_UPDATE_BY_ID_FAILURE";
export const USER_UPDATE_BY_ID_RESET = "USER_UPDATE_BY_ID_RESET";
